---
steps:
- name: hashicorp/terraform
  dir: ${_DEPLOYMENT_FOLDER}
  args:
  - init
- name: hashicorp/terraform
  dir: ${_DEPLOYMENT_FOLDER}
  args:
  - validate
- name: hashicorp/terraform
  dir: ${_DEPLOYMENT_FOLDER}
  args:
  - plan
- name: hashicorp/terraform
  dir: ${_DEPLOYMENT_FOLDER}
  args:
  - apply
  - -auto-approve
