---
steps:
- name: 'hashicorp/terraform:1.0.0'
  dir: ${_DEPLOYMENT_FOLDER}
  args:
  - init
- name: 'hashicorp/terraform:1.0.0'
  dir: ${_DEPLOYMENT_FOLDER}
  args:
  - validate
- name: 'hashicorp/terraform:1.0.0'
  dir: ${_DEPLOYMENT_FOLDER}
  args:
  - plan
  - -input=false
  - -out=tfplan
- name: 'hashicorp/terraform:1.0.0'
  dir: ${_DEPLOYMENT_FOLDER}
  args:
  - destroy
  - -auto-approve
# artifacts:
#   objects:
#     location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/plan/$BUILD_ID'
#     paths: ['cloudbuild-tf-plan.yaml', 'tfplan']
timeout: 1800s
