steps:
- id: Build Image
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_ARTIFACT_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}', '-f', '${_DOCKERFILE_PATH}', '.' ]
- id: Push Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_ARTIFACT_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}']
- id: Deploy to GKE
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./api/k8s-api.yaml
  - --location=${_GKE_LOCATION}
  - --cluster=${_GKE_CLUSTER}