steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_ARTIFACT_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}', '-f', '${_DOCKERFILE_PATH}', '.' ]