---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "api"
  namespace: "default"
  labels:
    app: "api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "api"
  template:
    metadata:
      labels:
        app: "api"
    spec:
      containers:
      - name: "api"
        image: us-central1-docker.pkg.dev/magnificent-pen-332209/node3tier/node3tier-api:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
        command:
          - "/cloud_sql_proxy"
          - "-instances=magnificent-pen-332209:us-central1:postgres-instance2=tcp:5432"
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "api-hpa"
  namespace: "default"
  labels:
    app: "api"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "api"
    apiVersion: "apps/v1"
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80