steps:
- name: node
  entrypoint: npm
  args: ['--prefix', 'web', 'install']
- name: node
  entrypoint: npm
  args: ['--prefix', 'web', 'test']
- id: Build Image
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 
          '--build-arg', 'PORT=${_PORT}',
          '--build-arg', 'API_HOST=${_API_HOST}',
          '-t', '${_ARTIFACT_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}', 
          '-f', '${_DOCKERFILE_PATH}', 
          '.' ]
- id: Push Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_ARTIFACT_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}:latest']
# - id: Customise K8s yaml
#   name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: "/bin/sh"
#   args: ['-c', 'cat ./api/k8s-api.yaml | sed s/{{attribute-to-replace}}/${_VAR-FROM-TRIGGER}/g > custom.yaml']
- id: Deploy to GKE
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./web/k8s-web.yaml
  - --image=${_ARTIFACT_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}:latest
  - --location=${_GKE_LOCATION}
  - --cluster=${_GKE_CLUSTER}
